### ISSUE TITLE
abortTime exceeded while waiting for videos to exist. videoRenderTimeout triggered before ffmpeg had a chance to wrap up

### ISSUE THREAD

**Issue by dapolJS** [webdriverio-community/wdio-video-reporter#105]
**Describe the bug**
Often when all tests pass, for some of them only video recording fails with following message from Video Reporter Done!:
abortTime exceeded while waiting for videos to exist.
videoRenderTimeout triggered before ffmpeg had a chance to wrap up
and runtime errror: 
ERROR @wdio/local-runner: Failed launching test session: Error: ENOENT: no such file or directory, stat '/datadisk/jenkins_node/workspace/name/_results_/name-21--name--name--CHROME--07-14-2023--05-28-22-765.mp4

**Log**
[0-25] 2023-07-14T03:31:07.653Z ERROR @wdio/local-runner: Failed launching test session: Error: ENOENT: no such file or directory, stat '/datadisk/jenkins_node/workspace/name/_results_/name-21--name--name--CHROME--07-14-2023--05-28-22-765.mp4
[0-25]     at Object.statSync (node:fs:1596:3)
[0-25]     at Object.statSync (/datadisk/jenkins_node/workspace/name/node_modules/graceful-fs/polyfills.js:319:16)
[0-25]     at /datadisk/jenkins_node/workspace/name/node_modules/wdio-video-reporter/src/helpers.js:158:70
[0-25]     at Array.map (<anonymous>)
[0-25]     at Object.waitForVideosToBeWritten (/datadisk/jenkins_node/workspace/name/node_modules/wdio-video-reporter/src/helpers.js:158:33)
[0-25]     at Video.onExit (/datadisk/jenkins_node/workspace/name/node_modules/wdio-video-reporter/src/index.js:263:13)
[0-25]     at process.<anonymous> (/datadisk/jenkins_node/workspace/name/node_modules/wdio-video-reporter/src/index.js:115:44)
[0-25]     at process.emit (node:events:525:35)
[0-25]     at process.emit (node:domain:489:12)
[0-25]     at process.emit.sharedData.processEmitHook.installedValue [as emit] (/datadisk/jenkins_node/workspace/name/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
[0-25] FAILED in chrome - /scenarios/specs/name.spec.js

When error happens even recorded file cant be found in among _results_ directories although it says video generated done.
On which test case error occurs is random, there are 28 test cases at the moment

**Expected behavior**
I would expect that video would be generated as per other test cases

**Environment (please complete the following information):**
 - **wdio-video-reporter version:** ["^3.4.0"]
 - **WebdriverIO version:** [8.1.0]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [18.15.0]
 - **NPM version:** [9.5.0]
 - **Browser name and version:** [Chrome 103]
 - **Platform name and version:** [Linux Rhel8]

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [chrome]

**Additional context**
how my configs look :

      video,
      {
        saveAllVideos: true, // If true, also saves videos for successful test cases
        videoSlowdownMultiplier: 10, // Higher to get slower videos, lower for faster videos [Value 1-100]
        videoRenderTimeout: 30 // Max seconds to wait for a video to render
      }
    ],
    [
      'allure',
      {
        outputDir: `${global.pathToReports}/allure-results`,
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: true,
        LOG: log4js.getLogger('default')
      }
    ],

**Comment by bhanuagarwal73** [comment]
I guess with WebdriverIO version: [8.1.0], you need to use dio-video-reporter version: ["^4...."]

**Comment by dapolJS** [comment]
@bhanuagarwal73  Hi!

Unfortunately with wdio-video-reporter "^4...." I cant use require, and need to use import statements.
And that is a problem as all of modules are using require statement in webdriverio framework and other files.

**Comment by bhanuagarwal73** [comment]
@dapolJS  try adding  "reporterSyncTimeout": 30000,

**Comment by dapolJS** [comment]
hi @bhanuagarwal73  I did increase the timeout but still get same problem

**Comment by Hammad-001** [comment]
hi @depol JS I am having the same issue. I have increased timeout to 100s. but still having same issue.

--- New test: Test case Name ---
Adding execution video attachment as /Users/User/Downloads/project_name/_results_/test-case-name--IPHONE14-IOS--08-21-2023--18-34-25-644.mp4
Incoming command: /session/:sessionId/screenshot => [screenshot]
- Screenshot!! (frame: 11)
Incoming command: /session/:sessionId/element => [element]
Incoming command: /session/:sessionId/screenshot => [screenshot]
- Screenshot!! (frame: 12)
Incoming command: /session/:sessionId/element => [element]
Incoming command: /session/:sessionId/element/0D000000-0000-0000-58A4-000000000000/click => [click]
Incoming command: /session/:sessionId/element => [element]
Incoming command: /session/:sessionId/screenshot => [screenshot]
- Screenshot!! (frame: 0)
Incoming command: /session/:sessionId/element/FE110000-0000-0000-58A4-000000000000/clear => [clear]
Incoming command: /session/:sessionId/element/FE110000-0000-0000-58A4-000000000000/value => [value]
Incoming command: /session/:sessionId/screenshot => [screenshot]
- Screenshot!! (frame: 1)
Incoming command: /session/:sessionId/elements => [elements]
Incoming command: /session/:sessionId/screenshot => [screenshot]
- Screenshot!! (frame: 2)
Incoming command: /session/:sessionId/element => [element]
Incoming command: /session/:sessionId/element/CE170000-0000-0000-58A4-000000000000/click => [click]
Incoming command: /session/:sessionId/element => [element]
Incoming command: /session/:sessionId/screenshot => [screenshot]
- Screenshot!! (frame: 3)
Incoming command: /session/:sessionId/element/1B000000-0000-0000-58A4-000000000000/enabled => [enabled]
Incoming command: /session/:sessionId/element => [element]
Incoming command: /session/:sessionId/screenshot => [screenshot]
- Screenshot!! (frame: 4)
Incoming command: /session/:sessionId/element/1B000000-0000-0000-58A4-000000000000/clear => [clear]
Incoming command: /session/:sessionId/element/1B000000-0000-0000-58A4-000000000000/value => [value]
Incoming command: /session/:sessionId/screenshot => [screenshot]
- Screenshot!! (frame: 5)
Incoming command: /session/:sessionId/element => [element]
Incoming command: /session/:sessionId/screenshot => [screenshot]
- Screenshot!! (frame: 6)
Incoming command: /session/:sessionId/element/17000000-0000-0000-58A4-000000000000/click => [click]
Incoming command: /session/:sessionId/element => [element]
Incoming command: /session/:sessionId/screenshot => [screenshot]
- Screenshot!! (frame: 7)
Incoming command: /session/:sessionId/elements => [elements]
Incoming command: /session/:sessionId/element => [element]
Incoming command: /session/:sessionId/element/E3170000-0000-0000-58A4-000000000000/click => [click]
ffmpeg command: "/Users/User/Downloads/project_name/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg" -y,-r,10,-i,"/Users/User/Downloads/project_name/_results_/rawSeleniumVideoGrabs/test-case-name-IPHONE14-IOS--08-21-2023--18-34-25-644/%04d.png",-vcodec,libx264,-crf,32,-pix_fmt,yuv420p,-vf,"scale=1200:trunc(ow/a/2)*2","setpts=40.0*PTS","/Users/User/Downloads/project_name/_results_/test-case-name-IPHONE14-IOS--08-21-2023--18-34-25-644.mp4"
Incoming command: /session/:sessionId/screenshot => [screenshot]
- Screenshot not available (frame: 8). Error: Error: ENOENT: no such file or directory, open '/Users/User/Downloads/project_name/_results_/rawSeleniumVideoGrabs/test-case-name-IPHONE14-IOS--08-21-2023--18-34-25-644/0008.png'..
Incoming command: /session/:sessionId => [:sessionId]
- Screenshot not available (frame: 9). Error: invalid session id: A session is either terminated or not started..

**Comment by erwinheitzman** [comment]
Can anyone create a small Github repo with a simple reproducible example of this?

**Comment by M-Hammad-Faisal** [comment]
- write 2-3 random test cases
- add wdio-video-reporter
- make sure your last test case is a bit longer

When wdio-video-reporter renders the last video, and try to attach it in last with the test case, but the session had already been terminated. It attaches the all videos except the last one.

If above three conditions are satisfied, then we get the session is terminated error that i have experienced.

**Comment by christian-bromann** [comment]
@M-Hammad-Faisal do you have a small GitHub repo for this we can check out?

**Comment by Avinash-Kannan** [comment]
Even I'm facing this today. It was working when test passed. But now, my last test failed. There seems to be error in playing video.

```
"video" Reporter:

Generated:[]

Video reporter Done!

Generated:[
  "C:\\Users\\regression--CHROME--02-16-2024--16-10-51-123.webm"
]


Video reporter Done!
abortTime exceeded while waiting for videos to exist.
```

**Comment by M-Hammad-Faisal** [comment]
@Avinash-Kannan can you provide small github repo of sample tests??
