### ISSUE TITLE
TypeError: browser.isAlertOpen is not a function while executing test script in Edge browser

### ISSUE THREAD

**Issue by Zarmeena** [webdriverio-community/wdio-video-reporter#108]
**Describe the bug**
'TypeError: browser.isAlertOpen is not a function' exception is thrown while executing the WDIO v8 test scripts in Edge browser. Same scripts are executing properly in Chrome.

**Log**
[0-0] TypeError in "Checkout Product.Add Item to Cart"
TypeError: browser.isAlertOpen is not a function
    at Video.onAfterCommand (file:///C:/Users/XXX1/Documents/QE%20Accelerators/CLI/Dev/Test%20Automation%20Accelerator%203.0/node_modules/wdio-video-reporter/dist/wdio-video-reporter.mjs:662:20)
    at Video.emit (node:events:525:35)
    at Video.emit (node:domain:489:12)
    at Array.forEach (<anonymous>)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.<anonymous> (file:///C:/Users/XXX1/Documents/QE%20Accelerators/CLI/Dev/Test%20Automation%20Accelerator%203.0/test/MobileWeb/Add%20Item%20to%20Cart.js?invalidateCache=0.5436009407404792:6:5)
![WDIO Video Reporter](https://github.com/webdriverio-community/wdio-video-reporter/assets/46337025/9f09eed2-4454-44a3-8fb3-e28b90cb714a)

**To Reproduce**
Set Up a basic WDIO v8 framework with Mocha.  A sample test script needs to be created and run through WDIO test runner . Following are the reporters added to WDIO conf file:
reporters: [     
	[
    'video', 
    {
        saveAllVideos: true,       // If true, also saves videos for successful test cases
        videoSlowdownMultiplier: 25, // Higher to get slower videos, lower for faster videos [Value 1-100]
    },
    'allure', 
	{
      outputDir: 'allure-results',
      disableWebdriverStepsReporting: false,
      disableWebdriverScreenshotsReporting: false,
	 }
	 ],'spec'
	 ]

**Expected behavior**
Test execution will be completed but an exception will occur during the report generation saying 'TypeError: browser.isAlertOpen is not a function'

**Environment (please complete the following information):**
 - **wdio-video-reporter version:** ^4.0.4
 - **WebdriverIO version:** ^8.15.6
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v18.16.1
 - **NPM version:** 9.5.1
 - **Browser name and version:** Microsoft Edge , Version 117.0.2045.36 (Official build) (64-bit)
 - **Platform name and version:** Windows 10

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : MS Edge
 - Version : 10

**Comment by HedgU4** [comment]
The same issue for the Firefox

**Comment by Hamfri** [comment]
Facing the same issue on Safari github runner macos-11

**Comment by Hamfri** [comment]
Downgrading to version ^3.5.0 seemed to fix the issue.

**Comment by Zarmeena** [comment]
> Downgrading to version ^3.5.0 seemed to fix the issue.

Okay.. Will try.. Thanks
