### ISSUE TITLE
remake a package from CommonJS to ES6 (rid out of files with .mjs extension)

### ISSUE THREAD

**Issue by soroko-sergey** [webdriverio-community/wdio-video-reporter#134]
now for me its impossible to use video-reporter with ES6. I can use video reporter till 3.5.0 version with ES6 for wdio v8, all newer versions are not working good. I catch errors about commonjs and es6

**Comment by christian-bromann** [comment]
@soroko-sergey thanks for raising the issue. Are you using WebdriverIO v8? If so you should have no issues using the service even if your tests are written in CJS. Can you provide error logs or a reproducible example?

**Comment by troyyer** [comment]
@christian-bromann 
i raised a discussion comment with a similar where i cant upgrade past video reporter v3.5 on either webdriverio v7 and v8 https://github.com/webdriverio-community/wdio-video-reporter/discussions/122

this is a current code sample having the issue
https://github.com/troyyer/wdiov8-sample-for-video-reporter/
