### ISSUE TITLE
Is this library getting the v9 upgrade?

### ISSUE THREAD

**Issue by brickfungus** [webdriverio-community/wdio-video-reporter#383]
I didn't see it on here https://github.com/webdriverio/webdriverio/issues/10362#issuecomment-2207866842

**Comment by christian-bromann** [comment]
@brickfungus you like to give us a hand and raise a PR?

**Comment by brickfungus** [comment]
I keep getting blank images here https://github.com/webdriverio-community/wdio-video-reporter/blob/66d9845bfa463b5653e94be8367479aabea6816e/src/index.ts#L206
I think because the browser has shut down by the time endSuite() is called, what do you think about removing it?

**Comment by christian-bromann** [comment]
> what do you think about removing it?

mhm 🤔 I am not sure if this is right, given there isn't a change in v9 that could impact this behavior.

**Comment by brickfungus** [comment]
[PR](https://github.com/webdriverio-community/wdio-video-reporter/pull/393)

**Comment by christian-bromann** [comment]
Thanks a lot! I tried to run the release pipeline but it fails due to some dependency issues, mind taking a look?
