### ISSUE TITLE
Shows error when using wdio-video-reporter with the latest version of webdriverio

### ISSUE THREAD

**Issue by paulohvalipio** [webdriverio-community/wdio-video-reporter#401]
**Describe the bug**
When running the project with version 9.0.7 of webdriverio and wdio-video-reporter 6.0.0, an error appears.

**Log**
test:oportunidade
wdio run config/android-wdio.conf.ts --spec .//tests//Modulos//Mobile//Oportunidade//Oportunidade.test.ts

2024-09-04T11:30:44.815Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///C:/project/config/android-wdio.conf.ts: No "exports" main defined in C:\project\node_modules\wdio-video-reporter\node_modules\@wdio\logger\package.json
Error: No "exports" main defined in C:\project\node_modules\wdio-video-reporter\node_modules\@wdio\logger\package.json

**To Reproduce**
wdio.config.ts:

`reporters: [[Video,{
    outputDir: './videos',      
    saveAllVideos: true,       
    videoSlowdownMultiplier: 3,
  }]],`

package.json:

`{
  "name": "project",
  "author": "",
  "license": "ISC",
  "main": "index.js",
  "devDependencies": {
    "@reportportal/agent-js-webdriverio": "^5.1.0",
    "@wdio/appium-service": "9.0.7",
    "@wdio/cli": "9.0.7",
    "@wdio/local-runner": "9.0.7",
    "@wdio/mocha-framework": "9.0.6",
    "@wdio/spec-reporter": "9.0.7",
    "appium": "^2.2.1",
    "appium-uiautomator2-driver": "3.7.7",
    "appium-uiautomator2-server": "7.0.23",
    "appium-xcuitest-driver": "5.12.1",
    "typescript": "^4.9.5",
    "wdio-video-reporter": "^6.0.0",
    "webdriverio": "9.0.7",
  },
}`

**Expected behavior**
Allow playing and recording videos with wdio-video-reporter with webdriverio 9.0.7.

**Environment (please complete the following information):**
 - **wdio-video-reporter version:** 6.0.0
 - **WebdriverIO version:** 9.0.7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 20.17.0
 - **NPM version:** 10.8.2
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: moto g42
 - OS: Android 13

**Additional context**

**Comment by christian-bromann** [comment]
This will be fixed with https://github.com/webdriverio/webdriverio/pull/13482
