### ISSUE TITLE
Does not run the project webdriverio 9.0.8 with wdio-video-reporter

### ISSUE THREAD

**Issue by paulohvalipio** [webdriverio-community/wdio-video-reporter#402]
**Describe the bug**
When running the project with wdio-video-reporter com o webdriverio 9.0.8 it displays the message

Error: Type check for option "reporters" failed: a reporter should be either a string in the format "wdio--reporter" or a function/class. Please see the docs for more information on custom reporters (https://webdriver.io/docs/customreporter)
at validateConfig (file:///C:/project/node_modules/@wdio/config/build/index.js:105:17)
at Launcher.run (file:///C:/project/node_modules/@wdio/cli/build/index.js:2164:5)

**Log**
Error: Type check for option "reporters" failed: a reporter should be either a string in the format "wdio--reporter" or a function/class. Please see the docs for more information on custom reporters (https://webdriver.io/docs/customreporter)
at validateConfig (file:///C:/project/node_modules/@wdio/config/build/index.js:105:17)
at Launcher.run (file:///C:/project/node_modules/@wdio/cli/build/index.js:2164:5)

**To Reproduce**
const video = require('wdio-video-reporter')

reporters: [
[video, {
saveAllVideos: true,
videoSlowdownMultiplier: 3,
videoRenderTimeout: 5,
}]
],

**Expected behavior**
The project must be run normally using wdio-video-reporter.

**Environment (please complete the following information):**
 - **wdio-video-reporter version:** 6.0.0
 - **WebdriverIO version:** 9.0.8
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 20.17.0
 - **NPM version:** 10.8.2
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: moto g42
 - OS: Android 13

**Additional context**

**Comment by Govind-Markad** [comment]
Have you got any solution?

**Comment by christian-bromann** [comment]
> const video = require('wdio-video-reporter')
> 
> reporters: [ [video, { saveAllVideos: true, videoSlowdownMultiplier: 3, videoRenderTimeout: 5, }] ],

This is not how you are suppose to add the reporter to the config, instead just do:

```ts
reporters: [
  ['video', {
    saveAllVideos: true,
    videoSlowdownMultiplier: 3,
    videoRenderTimeout: 5,
  }]
],
```
