### ISSUE TITLE
video generate in the cucumber framework

### ISSUE THREAD

**Issue by jay368** [webdriverio-community/wdio-video-reporter#453]
**Is your feature request related to a problem? Please describe.**
- I am using cucumber framework but onTestEnd is not executed inside code. So video generate is impossible.

( wdio-video-reporter/dist/wdio-video-reporter.mjs )
```
    onTestEnd(test) {
        console.log(`onTestEnd`)
        if (!__classPrivateFieldGet(this, _VideoReporter_record, "f")) {
            return;
        }
        this.clearScreenshotInterval();
        if (this.options.filenamePrefixSource === 'test' || this.isCucumberFramework) {
            this.testNameStructure.pop();
        }
        __classPrivateFieldGet(this, _VideoReporter_instances, "m", _VideoReporter_extendAllureReport).call(this);
        if (test.state === 'failed' || (test.state === 'passed' && this.options.saveAllVideos)) {
            this.addFrame();
            this.generateVideo();
        }
    }
```

**Describe the solution you'd like**
- Please allow us to generate videos in the cucumber framework.
- **cucumber framework hooks**
  - `before`
  - `after`
  - `beforeScenario`
  - `afterScenario`
  - `beforeStep`
  - `afterStep`

**Comment by christian-bromann** [comment]
Thanks for raising the issue @jay368 , any contributions would be much appreciated!
