### ISSUE TITLE
Unable to disable the rawSeleniumVideoGrabs screenshot.

### ISSUE THREAD

**Issue by iamatharva** [webdriverio-community/wdio-video-reporter#53]
**Is your feature request related to a problem? Please describe.**
Implemented the wdio-video-reporter for our test automation.
and we have set   `saveAllVideos: false`
As we want to save the videos only after the test failure.
But the rawSeleniumVideoGrabs are still getting generated even if the test are passed though the video is not getting generated but the screenshots are consuming memory in pipeline which i wanted to avoid.
Is there any way to disable it if the execution is passed.

**Describe the solution you'd like**
If the execution is passed then we should not save the rawSeleniumVideoGrabs.

**Describe alternatives you've considered**
No alternative idea

**Comment by presidenten** [comment]
The reporter dont know beforehand if the test will pass or fail. Seems Ill get a PR soon for the other open issue, when I merge it and bump all dependencies and such, I can have a look at deleting the screenshots for passing tests if the `saveAllVideos` flag is set.

**Comment by iamatharva** [comment]
Thank you for considering this and responding too quickly.

**Comment by presidenten** [comment]
@iamatharva 
Is it ok if I close this issue?
If you are still having problems, you could try to add add a `posttest`- or `poste2e`-hook in package.json scripts

```
  "scripts": {
    ...
    "e2e": "wdio wdio.conf.js",
    "poste2e": "rimraf _results_/rawSeleniumVideoGrabs"
  }
```

**Comment by iamatharva** [comment]
Yes, we can close this one.
The above suggestion works.
