### ISSUE TITLE
Support for Webdriverio 7?

### ISSUE THREAD

**Issue by cnelson** [webdriverio-community/wdio-video-reporter#56]
Are there any plans to make this module compatible with wdio v7?

**Comment by mikesalvia** [comment]
@cnelson I am currently on Webdriver.IO v7, I am not seeing any issues with Appium using an iOS simulator, so I would imagine the support is there for others.

Bit of other knowledge, this is a reporter, not a service, so changes to Webdriver.IO won't touch this as much, changes to `@wdio/cucumber-framework` or `@cucumber/cucumber` may. I am going to propose an update to the README.md.

**Comment by christian-bromann** [comment]
Fixed by #59
