### ISSUE TITLE
Move project to WebdriverIO Community Org

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-video-reporter#57]
Hey @presidenten  ,

first off, thank you for creating this plugin and extending the WebdriverIO ecosystem!

We have been looking into successful WDIO plugins like this one as we want to ensure that its development can be continued even if the original maintainer decides to move on. Therefore on behalf of the WebdriverIO community I would like to ask if you would be interested to move this repository into the [WebdriverIO Community](https://github.com/webdriverio-community) organisation. It would allow us to help maintain this package, automate a few things like releases and allow others to contribute to it and make the package even better. You would of course continue to have full access to it.

What do you think? Please let me know if you have any questions.

**Comment by presidenten** [comment]
Hi @christian-bromann,

Yes please. It sounds like a great idea. 

I like this project and feel quite bad that I cant give it the attention it deserves. 

Im leading the devops journey in my company and Im just swamped with things to do, which leaves me utterly fatigued on the weekends.

How do we proceed? 

I know there are some people waiting for it to be verified on wdio 7. I have checked and all tests go through and the diff is almost non-existant, so there shouldnt be any issues.

**Comment by christian-bromann** [comment]
> How do we proceed?

Here are the steps that are necessary to do this transition:

1. move this repository into the `webdriverio-community` organisation, see more information on that in the [GitHub docs](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)
2. then add [`wdio-user`](https://www.npmjs.com/~wdio-user) to the list of maintainer of the project on NPM

That should be it. Let me know if you have any questions. Thank you!

**Comment by presidenten** [comment]
Ok! Owenership should be `webdriverio-community` now and I think I also added wdio-user as an owner to wdio-video-reporter

I have never done it before. This is the output:
```bash
$ npm owner add wdio-user wdio-video-reporter
+ wdio-user (wdio-video-reporter)
npm notice
npm notice New minor version of npm available! 7.0.15 -> 7.13.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.13.0
npm notice Run npm install -g npm@7.13.0 to update!
npm notice
```

If you guys want, I would be up for a video meeting where I can explain how the code is structured, to help you get it up and running.

**Comment by christian-bromann** [comment]
@presidenten the repository transfer probably failed because I forgot to invite you to the org. I just did that so please try again.

> If you guys want, I would be up for a video meeting where I can explain how the code is structured, to help you get it up and running.

Would you mind schedule something as part of the [Open Office Hours](https://webdriver.io/community/openofficehours)?

**Comment by presidenten** [comment]
@christian-bromann 

I still get: `You don’t have the permission to create public repositories on webdriverio-community`

![image](https://user-images.githubusercontent.com/3883897/119016356-20b88d80-b99a-11eb-9eb2-3be794de6cf3.png)
