### ISSUE TITLE
Add a parameter to remove excess console messages

### ISSUE THREAD

**Issue by l1nk001** [webdriverio-community/wdio-video-reporter#76]
**Is your feature request related to a problem? Please describe.**
When I run more than 200 tests, I can't see my post scripts due to the output of video reporter : those 2 lines :  
```
this.write('\nGenerated:' + JSON.stringify(this.videos, undefined, 2) + '\n\n');
this.write(`\n\nVideo reporter Done!\n`);

```
**Describe the solution you'd like**
add a parameter to the wdio conf video reporter, that disables the this.write... 

**Describe alternatives you've considered**
I forked the repo and temp fixed it but it interferes with npm install

**Additional context**

**Comment by christian-bromann** [comment]
Sounds like a reasonable feature request. Any contributions are welcome!

**Comment by kerkeniakov** [comment]
https://github.com/webdriverio-community/wdio-video-reporter/pull/77

**Comment by christian-bromann** [comment]
Merged and released
