### ISSUE TITLE
Don't make screenshots if an alert is open

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-video-reporter#79]
see [#8351](https://github.com/webdriverio/webdriverio/issues/8351)

**Comment by robbiexiong** [comment]
do we have any update on this issue?

**Comment by SDLarmo** [comment]
Hi. I've also faced this issue and made a PR that fixes it. Please check #106

**Comment by erwinheitzman** [comment]
This should now be resolved. Also the implementation you did @SDLarmo was Chromium specific. I have kept the behavior and changed it to a webdriver alternative so that it works for all browsers 👍
