### ISSUE TITLE
browser.getMetrics is not a function when using wdio-video-reporter alongside devtools

### ISSUE THREAD

**Issue by chrisplim** [webdriverio-community/wdio-video-reporter#82]
Description
---
browser.getMetrics is not a function when using wdio-video-reporter alongside devtools

Reproduction Steps
---
https://github.com/chrisplim/wdio-video-reporter-bug
1. Setup, and run the example test. To see the test pass
  ```
  git clone git@github.com:chrisplim/wdio-video-reporter-bug.git
  cd wdio-video-reporter-bug
  npm install
  npm run wdio
   ```
2.  Uncomment the code in wdio.conf.js between the UNCOMMENT_ME blocks and run the test again to see the error message.
```
# uncomment code in wdio.conf.js between the UNCOMMENT_ME blocks
npm run wdio
```

**Expected behavior**
---
I expect that I should be able to use the devtools functionality like `browser.getMetrics` while also writing videos from the wdio-video-reporter in a test; and that test should pass without any errors.

Environment
---
 - **wdio-video-reporter version:** 3.2.3
 - **WebdriverIO version:** 7.24.1
 - **Mode:** wdio
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v16.15.0
 - **NPM version:** 8.5.5
 - **Browser name and version:** Chrome 105.0.5195.125 
 - **Platform name and version:** macOS Monterey 12.3.1

Notes
---
Related issue comment:
https://github.com/webdriverio/webdriverio/issues/7778#issuecomment-985598891

**Comment by christian-bromann** [comment]
Thanks for reporting. This is unrelated to the video reporter and should be reported in the main WebdriverIO project. Join our  [Discord](https://discord.webdriver.io) server if you have further questions. Thanks.
