### ISSUE TITLE
The demo package is using @wdio/sync which isn't compatible with Node v16

### ISSUE THREAD

**Issue by Diazole** [webdriverio-community/wdio-video-reporter#84]
**Describe the bug**

https://github.com/webdriverio-community/wdio-video-reporter/blob/v3.3.0/demo/package.json

- The demo package is using `@wdio/sync` which isn't compatible with Node v16
- The package version is `3.0.0` but the tag is `3.3.0`.

**Environment (please complete the following information):**
 - **wdio-video-reporter version:** 3.3.0

**Comment by christian-bromann** [comment]
We have updated the demo to not use sync anymore. Thanks for reporting.
