### ISSUE TITLE
Support for webdriver v8

### ISSUE THREAD

**Issue by kopax-polyconseil** [webdriverio-community/wdio-video-reporter#85]
**Is your feature request related to a problem? Please describe.**

I would like to use this reporter with wdio v8

**Describe the solution you'd like**

Add support for v8

**Describe alternatives you've considered**

Stay in webdriver 7

**Additional context**

latest 3.3.0 use this tree depenendency:

```ts
└─┬ wdio-video-reporter@3.3.0
  ├─┬ @wdio/allure-reporter@7.26.0
  │ └── @wdio/reporter@7.26.0 deduped
  └── @wdio/reporter@7.26.0

```

**Comment by christian-bromann** [comment]
@kopax-polyconseil what are the issues you are currently experiencing when using the reporter with v8?

**Comment by espekkaya** [comment]
Hi @christian-bromann, it's ok to create mp4 videos file but when we integrate with allure reporter, it takes wrong mp4 file path. So in allure report, there has an video but it shows nothing.

**Comment by questUser** [comment]
Hello @christian-bromann, 
I am seeing  ERROR: webdriver: Request failed with status 404 due to invalid session id: invalid session id
with "wdio-video-reporter": "^3.5.0"

**Comment by christian-bromann** [comment]
Any contribution that fixes support for `v8` is much appreciated.

**Comment by a7madgamal** [comment]
I'm willing to look into it but I'm new to the project
what exactly is the issue, or where should I begin looking?

**Comment by christian-bromann** [comment]
> what exactly is the issue, or where should I begin looking?

The current service seems to only work with WebdriverIO v7 and not v8. Can you verify that WebdriverIO v8 doesn't work with this service? If yes , why?

**Comment by christian-bromann** [comment]
I updated the reporter to work with v8 and will release within the next days.
