### ISSUE TITLE
Add an option to take screenshots at regular intervals during each test

### ISSUE THREAD

**Issue by wadjei** [webdriverio-community/wdio-video-reporter#90]
**Is your feature request related to a problem? Please describe.**
Videos are made up from screen shots taken after commands are sent, so play very quickly unless slowed. Some ui changes between the commands may also be lost.

**Describe the solution you'd like**
An option to capture the screen at regular intervals while the test runs.

**Describe alternatives you've considered**
Proposed implementation at https://github.com/webdriverio-community/wdio-video-reporter/pull/89

**Comment by christian-bromann** [comment]
Implemented in https://github.com/webdriverio-community/wdio-video-reporter/pull/89
