### ISSUE TITLE
Proposal: Add option to only record last failed test when using specFileRetries

### ISSUE THREAD

**Issue by WillBrock** [webdriverio-community/wdio-video-reporter#95]
Recording a video on every test can take up a lot of resources. On our current setup we use `specFileRetries` and we don't care about videos of passing tests but we do care about failing tests. When using `specFileRetries` an option can be added so that it will only start recording a test if it is on the last retry. 

Scenario:
`specFileRetries` is set to 3. A test has failed 2 times, now on the third run of the test it will record that test.

The new option could be `onlyRecordLastFailure`.

We've been using this for a couple of years with a locally modified version of this package.

**Comment by christian-bromann** [comment]
I think this makes totally sense. I would suggest to make this an optional behavior, given that users might also be interested in previous failure especially if a test fails for different reasons. What do you think?>

Any contributions would be appreciated.

**Comment by WillBrock** [comment]
Cool, yeah that sounds good.

I'll also update the packages for v8 while I'm at it.

**Comment by christian-bromann** [comment]
> I'll also update the packages for v8 while I'm at it.

🎉

**Comment by christian-bromann** [comment]
> I'll also update the packages for v8 while I'm at it.

I've already done this, still interested in this feature?

**Comment by WillBrock** [comment]
Yes, I actually worked on it last night. I just need to create some tests and I'll submit it.

**Comment by christian-bromann** [comment]
Released in `v5.1.0`
